services:
  express-database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=user
      - POSTGRES_DB=users
    ports:
      - "5439:5432"
    volumes:
      - users-database:/var/lib/postgresql/data

volumes:
  users-database: