services:
  express-database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=user
      - POSTGRES_DB=users
    ports:
      - "5439:5432"
    volumes:
      - users-database:/var/lib/postgresql/data
  redis-cache:
    image: redis
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"

volumes:
  users-database: